; Ambientes do PlatformIO

[platformio]
description = Projeto para controlar robôs com o controle DualSense (PS5) usando ESP32

[env]
platform = espressif32@^6.13.0
framework = espidf
monitor_speed = 115200
build_flags =
    ; flags de avisos
    -Wall                   ; habilitando todos os avisos do compilador
    -Wextra                 ; avisos extras
    -Wshadow                ; avisos de variáveis com mesmo nome em escopos diferentes
    -Wundef                 ; avisos de macros não definidas
    -Wconversion            ; avisos de conversão implícitas de tipos
    -Wdouble-promotion      ; avisos de promoção de float para double
    -Werror                 ; Transforma warnings em erros

    ; flags para otimizações de memória e execução
    -fno-exceptions         ; desabilitando exceções
    -fno-rtti               ; desabilitando run-time type information
    -ffunction-sections     ; separa funções por seção na memória para o garbage collector do linker limpar oq não usa
    -fdata-sections         ; separa as variáveis por seção também (tudo na compilação)
    -ffast-math             ; otimizações matemáticas
    -fno-threadsafe-statics ; desabilita inicialização de variáveis estáticas em tempo de execução
    -Os                     ; Otimização -Os com foco em reduzir o tamanho do código

    ; flags para o padrão C++
    -std=gnu++23            ; padrão C++23

    # flags para hardware
    -DCONFIG_FREERTOS_HZ=1000
    -DCONFIG_ESP32_DEFAULT_CPU_FREQ_240=y

[env:Chihiro]
board = esp32doit-devkit-v1
build_flags =
    ${env.build_flags}
    -D CHIHIRO

lib_deps =
    https://github.com/rodneybakiskan/ps5-esp32.git
