; Ambientes do PlatformIO

[platformio]
description = Projeto para controlar robôs com o controle DualSense (PS5) usando ESP32

[env]
platform = espressif32@^6.13.0
framework = espidf
board = esp32doit-devkit-v1
board_build.f_flash = 40000000L
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_src_flags = ; flags aplicadas apenas nos meus códigos (pasta src e dependências)
    ; flags de avisos
    -Wall                   ; habilitando todos os avisos do compilador
    -Wextra                 ; avisos extras
    -Werror                 ; Transforma warnings em erros
    -Wshadow                ; avisos de variáveis com mesmo nome em escopos diferentes
    -Wundef                 ; avisos de macros não definidas
    -Wconversion            ; avisos de conversão implícitas de tipos
    -Wdouble-promotion      ; avisos de promoção de float para double

    ; Desabilitando alguns warnings por causa do ESP-IDF escrito em C
    -Wno-error=undef
    -Wno-error=missing-field-initializers
    -Wno-error=conversion

    ; flags para otimizações de memória e execução
    -fno-exceptions         ; desabilitando exceções
    -fno-rtti               ; desabilitando run-time type information
    -ffunction-sections     ; separa funções por seção na memória para o garbage collector do linker limpar oq não usa
    -fdata-sections         ; separa as variáveis por seção também (tudo na compilação)
    -ffast-math             ; otimizações matemáticas
    -fno-threadsafe-statics ; desabilita inicialização de variáveis estáticas em tempo de execução
    -Os                     ; Otimização -Os com foco em reduzir o tamanho do código
build_flags = ; flags para tudo, incluindo esp-idf
    ; flags para o padrão C++
    -std=gnu++23            ; padrão C++23

[env:Chihiro]
build_flags =
    ${env.build_flags}
    -D CHIHIRO               ; macro de pré-processamento

[Hockey] ; Ambiente abstrato para hockey
build_flags =
    ${env.build_flags}
    -D HOCKEY                ; macro de pré-processamento

[env:Hockey-Ana]
extends = Hockey
build_flags =
    ${Hockey.build_flags}
    -D ANA

[env:Hockey-Froes]
extends = Hockey
build_flags =
    ${Hockey.build_flags}
    -D FROES

[env:Hockey-Cerqueira]
extends = Hockey
build_flags =
    ${Hockey.build_flags}
    -D CERQUEIRA